### ISSUE TITLE
Automated LLVM FIs failing in coreclr build step

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/llilc#990]
Four tests seem to have started timing out with the most recent FI from LLVM, appearing at Microsoft/llvm#127 and repeating in Microsoft/llvm#128.  We'll have to add exclusions for them:

```
JIT\jit64\opt\cse\hugeSimpleExpr1\hugeSimpleExpr1.cmd
JIT\jit64\opt\cse\HugeArray\HugeArray.cmd
JIT\Regression\VS-ia64-JIT\V2.0-Beta2\b311420\b311420\b311420.cmd
JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b399444\b399444b\b399444b.cmd
```

**Comment by AndyAyersMS** [comment]
I took at look at `HugeArray`. It took 10.5 hours to compile! Almost all the time was spent in `PEI::replaceFrameIndicies` and under that in `usesTheStack`. 

Looks like `eliminateFrameIndex` is quadratic, it walks all instructions and (at least in our case) calls `usesTheStack` which ends up walking a large fraction of instrucions over again.

We could probably work around this by forcing a frame pointer on for large methods.

**Comment by AndyAyersMS** [comment]
Looks like this is fixed in  (r256730)[https://github.com/Microsoft/llvm/commit/f124911f7a6ec79c44e71a3dccac8733c8ded458] but that didn't auto-FI into the MS branch....

**Comment by JosephTremoulet** [comment]
The auto-FI hit some sort of issue with new coreclr bits and/or pyhton each of the past two days:

```
02:34:39 C:\jenkins\workspace\zzzllilc-check\coreclr>echo off 
02:34:39 Commencing CoreCLR Repo build
02:34:40 
02:34:40 Checking pre-requisites...
02:34:40 
02:34:50 Commencing build of native components for Windows_NT.x64.Debug
02:34:50 
02:35:05 -- The C compiler identification is MSVC 18.0.31101.0
02:35:07 -- The CXX compiler identification is MSVC 18.0.31101.0
02:35:07 -- Check for working C compiler using: Visual Studio 12 2013 Win64
02:35:09 -- Check for working C compiler using: Visual Studio 12 2013 Win64 -- works
02:35:09 -- Detecting C compiler ABI info
02:35:10 -- Detecting C compiler ABI info - done
02:35:10 -- Check for working CXX compiler using: Visual Studio 12 2013 Win64
02:35:12 -- Check for working CXX compiler using: Visual Studio 12 2013 Win64 -- works
02:35:12 -- Detecting CXX compiler ABI info
02:35:13 -- Detecting CXX compiler ABI info - done
02:35:13 -- The ASM_MASM compiler identification is MSVC
02:35:13 -- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/ml64.exe
02:35:14 -- Configuring done
02:35:21 -- Generating done
02:35:21 -- Build files have been written to: C:/jenkins/workspace/zzzllilc-check/coreclr/bin/obj/Windows_NT.x64.Debug
02:35:22 generating clretwallmain.h and etmdummy.h
02:35:23 Traceback (most recent call last):
02:35:23   File "C:\jenkins\workspace\zzzllilc-check\coreclr\src\scripts\genWinEtw.py", line 9, in <module>
02:35:23     from genXplatEventing import * 
02:35:23   File "C:\jenkins\workspace\zzzllilc-check\coreclr\src\scripts\genXplatEventing.py", line 13, in <module>
02:35:23     from sets import Set
02:35:23 ImportError: No module named 'sets'
02:35:23 Failed to generate ETW specific files.
02:35:23 Build step 'Execute Windows batch command' marked build as failure
02:35:25 [BFA] Scanning build for known causes...
```

**Comment by AndyAyersMS** [comment]
I think this is fallout from the work to enable ETW generation (dotnet/coreclr#2846) -- sounds like it needs some revamping.

**Comment by erozenfeld** [comment]
I saw this locally and worked around it by changing my path to point to python27 instead of python34.

**Comment by JosephTremoulet** [comment]
Hmm.  The [CoreCLR build instructions](https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md#python) do indeed point to 2.7.  @mmitche, should something be changed on the machine(s) running llvmfi-buildflow to use 2.7 instead of 3.4, at least for the coreclr build?

**Comment by mmitche** [comment]
@JosephTremoulet IIRC 3.4 isn't even installed at all (on Windows)  2.7 should be what is on the path.

**Comment by JosephTremoulet** [comment]
@mmitche: something has put 3.4 directories on the path:

```
02:34:39 C:\jenkins\workspace\zzzllilc-check>set PATH=C:\Program Files (x86)\Java\jre1.8.0_45\bin;C:\Program Files\Internet Explorer;;C:\Python34\;C:\Python34\Scripts;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\AegisTools\Bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC;C:\Program Files\SourceGear\Common\DiffMerge\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Java\jre1.8.0_45\bin 
02:34:39 
02:34:39 C:\jenkins\workspace\zzzllilc-check>cd coreclr 
02:34:39 
02:34:39 C:\jenkins\workspace\zzzllilc-check\coreclr>build.cmd
02:34:39 
02:34:39 C:\jenkins\workspace\zzzllilc-check\coreclr>echo off 
02:34:39 Commencing CoreCLR Repo build
```

Should I update this part of the job definition:
```
set PATH=%PATH:"=%

cd coreclr
build.cmd
```
to
```
set PATH=C:\Python27\;C:\Python27\Scripts;%PATH:"=%

cd coreclr
build.cmd
```

maybe?

**Comment by mmitche** [comment]
@JosephTremoulet That directory doesn't actually exist on the build machines.

**Comment by JosephTremoulet** [comment]
Then the test step is certain to fail:
```
cd coreclr\tests
set PATH=%PATH:"=%

C:\Python34\python %WORKSPACE%\llvm\tools\llilc\test\llilc_runtest.py -a x64 -b debug -r ..\..\test -j %WORKSPACE%\build\bin\RelWithDebInfo\llilcjit.dll -c %WORKSPACE%\coreclr\bin\Product\Windows_NT.x64.Debug
```

I've been looking at zzzllvmfi-buildflow on mmitche-001; is that not the right place anymore?

**Comment by JosephTremoulet** [comment]
Seems like it couldn't hurt, so I updated the configs as described and we'll see if it has any effect on tonight's run.

**Comment by JosephTremoulet** [comment]
...and the nightly run failed before getting to the coreclr build due to a merge conflict.

**Comment by JosephTremoulet** [comment]
Last night's automated FI still failed due to new CoreCLR tests, but it did at least get through the coreclr build.
